project:
  type: website
  output-dir: docs

website:
  title: Pyground 🐍
  navbar:
    left:
      - index.qmd
      - about.qmd
  page-footer:
    right: "[Made with Quarto](https://quarto.org/docs/websites)"
    center: <a href="https://github.com/jben-hun"><i class="bi bi-github"></i> <b>JBen</b></a>

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full